### ISSUE TITLE
Invalid licence

### ISSUE THREAD

**Issue by stef-pellegrino** [xiaguliuxiang/dbvisualizer-agent#11]
Hi,

On Linux 64bit, with last release dbvis 14.0.2 I get

Invalid seal in license key file!

Any idea ?

Thanks

**Comment by xiaguliuxiang** [comment]
`CentOS 7.9.2009 x86_64` 实测可以激活 `DbVisualizer Pro 14.0.2`，注意使用帮助的第二条。
默认的`License id`已经进入软件服务商的黑名单，建议使用自定义的`License id`，具体参考上一步的帮助输出。
使用如下`License Key`测试可以激活
```
# DbVisualizer Pro License - 侠骨留香/ChinaPYG 2019
dbvis.license.activation=2019-09-09
dbvis.license.edition=Personal
dbvis.license.expire=2099-12-31
dbvis.license.id=stef-pellegrino
dbvis.license.name=侠骨留香
dbvis.license.org=ChinaPYG
dbvis.license.product=DbVisualizer
dbvis.license.seal=MCwCFED9A5CEQWjxVh6vP8sNkKQIOZAAAhQ2HYOohyWRLvLVt7igMw+QBVcBDw==
dbvis.license.upgrade.expire=2099-12-31
dbvis.license.version=2019.09.09
```

**Comment by stef-pellegrino** [comment]
Thanks, but same issue !
I'm using debian 11 :(

**Comment by stef-pellegrino** [comment]
Oops, I'm confused, sorry my fault.. Wrong folder.

My mistake :(
Thanks anyway for you help :+1:
