### ISSUE TITLE
10.0.26 修改dbvis.vmoptions 之后, dbvis.exe 打不开 

### ISSUE THREAD

**Issue by zh0122** [xiaguliuxiang/dbvisualizer-agent#2]
尝试过把agent.jar 放到不同文件夹, 包括不需要管理员权限, 和不包含中文和空格的路径, 打开dbvis.exe没有反应, 任务管理器里面闪一下就没有了 , .dbvis/logs/ 下面不会生成新的log ,  请问是什么原因? 谢谢
---
Product: DbVisualizer Free 10.0.26 [Build #3028]
OS: Windows 10
OS Version: 10.0
OS Arch: amd64
Java Version: 1.8.0_241
Java VM: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Java Home: d:\develop\java\jdk1.8.0_241\jre
DbVis Home: C:\Program Files\DbVisualizer
User Home: C:\Users\zh0122
PrefsDir: C:\Users\zh0122\.dbvis
SessionId: 387
BindDir: null

**Comment by zdtdtel** [comment]
你按照大佬的步骤一步一步来, V11 版本的我都已经破解成功了.......... 你再好好试试吧.....

**Comment by xiaguliuxiang** [comment]
也许是agent不行了
