### ISSUE TITLE
希望尽快支持到v11的版本

### ISSUE THREAD

**Issue by xuwenkeke** [xiaguliuxiang/dbvisualizer-agent#3]
:muscle::muscle:

**Comment by zdtdtel** [comment]
> 💪💪

现在 V11 版本就可以用呀........,  你是不是就没测试呀.???

**Comment by pedoc** [comment]
支持最新11.0.4版本，设置方式

1.拷贝dbvisualizer-agent-1.0.2.jar到安装目录和%homepath%\.dbvis目录下
2.在%homepath%\.dbvis目录新建一个user.vmoptions文件
3.在user.vmoptions里填写-javaagent:%homepath%\.dbvis\dbvisualizer-agent-1.0.2.jar

%homepath% 替换为变量实际值
不确定为什么直接修改安装目录下的dbvis.vmoptions为什么不生效
不确定为什么安装目录和%homepath%下都必须存在dbvisualizer-agent-1.0.2.jar，否则不生效

**Comment by beermedlar** [comment]
> 支持最新11.0.4版本,设置方式
> 
> 1._db 视觉器代理
> -1.0.2.jar=%homepath%.dbvis=2.%homepath%.dbvis=user.vmoptions=3.user.vmoptions\javaagent：%homepath%.dbvis\
> dbvisizer-代理-1.0.2.jar. jar
> 
> %homepath%
> [dbvis.vmoptions]
> %= db 视觉器代理 -1.0.2.jar，]

试了下，并不行呀

**Comment by beermedlar** [comment]
> 支持最新11.0.4版本，设置方式
> 
> 1.拷贝dbvisualizer-agent-1.0.2.jar到安装目录和%homepath%.dbvis目录下
> 2.在%homepath%.dbvis目录新建一个user.vmoptions文件
> 3.在user.vmoptions里填写-javaagent:%homepath%.dbvis\dbvisualizer-agent-1.0.2.jar
> 
> %homepath% 替换为变量实际值
> 不确定为什么直接修改安装目录下的dbvis.vmoptions为什么不生效
> 不确定为什么安装目录和%homepath%下都必须存在dbvisualizer-agent-1.0.2.jar，否则不生效

~~试了下并不行啊~~
使用默认的不行，重新生成的Key可以了

**Comment by abis1312** [comment]
I used the regenerated key. Still not working

**Comment by xiaguliuxiang** [comment]
此工具并不太适合我的应用场景早已卸载，这里也就懒得更新了，商业使用的记得支持正版哦！

**Comment by zdtdtel** [comment]
@xiaguliuxiang 那你现在用的是啥工具呀, 交流交流

**Comment by xiaguliuxiang** [comment]
> @xiaguliuxiang 那你现在用的是啥工具呀, 交流交流

数据库方面用的 Navicat Premium 15 + DBeaverEE， Redis 用 RedisDesktopManager，MongoDB 用 NoSQLBooster for MongoDB，暂时用着这几个。

**Comment by zdtdtel** [comment]
@xiaguliuxiang 你使用的 DBeaverEE 和 NoSQLBooster for MongoDB 是破解的吗?

**Comment by xiaguliuxiang** [comment]
> @xiaguliuxiang 你使用的 DBeaverEE 和 NoSQLBooster for MongoDB 是破解的吗?

是的，呃，很不好意思。。。溜了溜了

**Comment by zdtdtel** [comment]
@xiaguliuxiang DBeaverEE 最新的破解版, 到哪个版本号了?

**Comment by xiaguliuxiang** [comment]
> @xiaguliuxiang DBeaverEE 最新的破解版, 到哪个版本号了?

官网什么版本就是什么版本喽，比如目前Early Access版本是7.3.0.202012061950
