### ISSUE TITLE
upgrade 11.0.6

### ISSUE THREAD

**Issue by stef-pellegrino** [xiaguliuxiang/dbvisualizer-agent#7]
Hi,
Any chance to get the agent for 11.0.6 ?

**Comment by xiaguliuxiang** [comment]
dbvisualizer-agent-1.0.3 同样适用于 DbVisualizer ver. 11.0.6，agent 不需要更新，Windows 7 x64 已验证。

**Comment by stef-pellegrino** [comment]
Thanks, sorry I didn't notice.
